/**
 * @fileoverview gRPC-Web generated client stub for pb
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v5.26.1
// source: proto/chess.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.pb = require('./chess_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.pb.ChessApiClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.pb.ChessApiPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pb.MakeMoveRequest,
 *   !proto.pb.MakeMoveResponse>}
 */
const methodDescriptor_ChessApi_MakeMove = new grpc.web.MethodDescriptor(
  '/pb.ChessApi/MakeMove',
  grpc.web.MethodType.UNARY,
  proto.pb.MakeMoveRequest,
  proto.pb.MakeMoveResponse,
  /**
   * @param {!proto.pb.MakeMoveRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pb.MakeMoveResponse.deserializeBinary
);


/**
 * @param {!proto.pb.MakeMoveRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pb.MakeMoveResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pb.MakeMoveResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.pb.ChessApiClient.prototype.makeMove =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/pb.ChessApi/MakeMove',
      request,
      metadata || {},
      methodDescriptor_ChessApi_MakeMove,
      callback);
};


/**
 * @param {!proto.pb.MakeMoveRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pb.MakeMoveResponse>}
 *     Promise that resolves to the response
 */
proto.pb.ChessApiPromiseClient.prototype.makeMove =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/pb.ChessApi/MakeMove',
      request,
      metadata || {},
      methodDescriptor_ChessApi_MakeMove);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pb.NewGameRequest,
 *   !proto.pb.NewGameResponse>}
 */
const methodDescriptor_ChessApi_NewGame = new grpc.web.MethodDescriptor(
  '/pb.ChessApi/NewGame',
  grpc.web.MethodType.UNARY,
  proto.pb.NewGameRequest,
  proto.pb.NewGameResponse,
  /**
   * @param {!proto.pb.NewGameRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pb.NewGameResponse.deserializeBinary
);


/**
 * @param {!proto.pb.NewGameRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pb.NewGameResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pb.NewGameResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.pb.ChessApiClient.prototype.newGame =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/pb.ChessApi/NewGame',
      request,
      metadata || {},
      methodDescriptor_ChessApi_NewGame,
      callback);
};


/**
 * @param {!proto.pb.NewGameRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pb.NewGameResponse>}
 *     Promise that resolves to the response
 */
proto.pb.ChessApiPromiseClient.prototype.newGame =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/pb.ChessApi/NewGame',
      request,
      metadata || {},
      methodDescriptor_ChessApi_NewGame);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pb.PingRequest,
 *   !proto.pb.PingResponse>}
 */
const methodDescriptor_ChessApi_Ping = new grpc.web.MethodDescriptor(
  '/pb.ChessApi/Ping',
  grpc.web.MethodType.UNARY,
  proto.pb.PingRequest,
  proto.pb.PingResponse,
  /**
   * @param {!proto.pb.PingRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pb.PingResponse.deserializeBinary
);


/**
 * @param {!proto.pb.PingRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pb.PingResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pb.PingResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.pb.ChessApiClient.prototype.ping =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/pb.ChessApi/Ping',
      request,
      metadata || {},
      methodDescriptor_ChessApi_Ping,
      callback);
};


/**
 * @param {!proto.pb.PingRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pb.PingResponse>}
 *     Promise that resolves to the response
 */
proto.pb.ChessApiPromiseClient.prototype.ping =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/pb.ChessApi/Ping',
      request,
      metadata || {},
      methodDescriptor_ChessApi_Ping);
};


module.exports = proto.pb;

